import{S as u,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const d="44783480-725b805b80ef605c474d620ee";async function p(n){const t=`https://pixabay.com/api/?key=${d}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const r=await fetch(t);if(!r.ok)throw new Error("Network response was not ok");return(await r.json()).hits}catch(r){throw console.error("Error fetching images:",r),r}}function m(n){const t=document.getElementById("gallery");if(t.innerHTML="",n.length===0){f();return}const r=n.map(e=>`
   <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}">
        <div class="info">
          <p>Likes: <span class="number">${e.likes}</span></p>
          <p>Views: <span class="number">${e.views}</span></p>
          <p>Comments: <span class="number">${e.comments}</span></p>
          <p>Downloads: <span class="number">${e.downloads}</span></p>
        </div>
      </a>
    `).join("");t.innerHTML=r,new u(".gallery a").refresh()}function f(){const n=document.getElementById("gallery");n.innerHTML="<p>Sorry, there are no images matching your search query. Please try again!</p>"}const y=document.getElementById("searchForm"),i=document.getElementById("search-input"),l=document.querySelector(".loader"),g=document.getElementById("gallery");y.addEventListener("submit",async function(n){n.preventDefault();const t=i.value.trim();if(!t){c.error({title:"Error",message:"Please enter a search query."});return}try{h();const r=await p(t);m(r),i.value=""}catch(r){console.error("Error searching images:",r),c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{w()}});function h(){l.style.display="block",g.innerHTML=""}function w(){l.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
