import{S as d,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(r){if(r.ep)return;r.ep=!0;const n=e(r);fetch(r.href,n)}})();const f="44783480-725b805b80ef605c474d620ee";function m(s){const t=`https://pixabay.com/api/?key=${f}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(t).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>e.hits).catch(e=>{throw console.error("Error fetching images:",e),e})}let i;function p(){i=new d(".gallery a")}function h(){i&&i.refresh()}function y(s){const t=document.getElementById("gallery");if(t.innerHTML="",s.length===0){g();return}const e=s.map(o=>`
   <a href="${o.largeImageURL}" class="gallery-item">
        <img src="${o.webformatURL}" alt="${o.tags}">
        <div class="info">
          <p>Likes: <span class="number">${o.likes}</span></p>
          <p>Views: <span class="number">${o.views}</span></p>
          <p>Comments: <span class="number">${o.comments}</span></p>
          <p>Downloads: <span class="number">${o.downloads}</span></p>
        </div>
      </a>
    `).join("");t.innerHTML=e}function g(){const s=document.getElementById("gallery");s.innerHTML="<p>Sorry, there are no images matching your search query. Please try again!</p>"}const L=document.getElementById("searchForm"),l=document.getElementById("search-input"),u=document.querySelector(".loader"),b=document.getElementById("gallery");p();L.addEventListener("submit",function(s){s.preventDefault();const t=l.value.trim();if(!t){c.error({title:"Error",message:"Please enter a search query."});return}w(),m(t).then(e=>{y(e),l.value="",h()}).catch(e=>{console.error("Error searching images:",e),c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}).finally(()=>{E()})});function w(){u.style.display="block",b.innerHTML=""}function E(){u.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
